# Generated by Django 5.0.1 on 2024-01-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
